{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pytestapp.serviceAccountName" . }}
  labels:
{{ include "pytestapp.labels" . | nindent 4 }}
{{- end -}}
